version: "3"
services:
  app:                # frontend
    build: ./app
    container_name: frontend
    ports:
      - "80:80"       # map local port 80 â†’ container port 80

  api:                # backend
    build: ./api
    container_name: backend
