services:
  api:
    build: ./api
    container_name: api
    expose:
      - "8080"

  app:
    build: ./app
    container_name: app
    ports:
      - "80:80"
    environment:
      API_HOST: api
    depends_on:
      - api
